### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by colinical** [userofbricks/Expanded-Combat#66] opened 2024-06-04 18:21 UTC
all of the melee weapons except for the great hammer, flail, and mace randomly lost their textures
mc 1.20.1
forge 47.2.0
expanded combat 3.1.2

**Comment by userofbricks** [comment] 2024-06-15 17:57
this is realated if not the same as #55 and have tested extensively for this issue and have not been able to reproduce it at all. for now this means nothing can be done.

**Comment by liavnk** [comment] 2024-07-24 19:00
@userofbricks i was able to reproduce it whilst creating my own modpack

Version: 1.20.1
Platform: neoforge 47.1.106

Screenshot:
![image](https://github.com/user-attachments/assets/8b070628-21c1-4784-8ac3-5c6ab48a341f)

Mods-List:
- [1.20-1.20.1]+Comics+Bubbles+Chat-1.3.4
- accessories_cclayer-7.4.0-alpha.15+1.20
- accessories-1.0.0-alpha.27+1.20-neoforge
- AchievementOptimizer-1.20.1-1.0.5
- adaptive_performance_tweaks_1.20.1-11.1.0
- adaptive_performance_tweaks_core_1.20.1-11.1.0
- adaptive_performance_tweaks_gamerules_1.20.1-11.1.0
- adaptive_performance_tweaks_items_1.20.1-11.1.0
- adaptive_performance_tweaks_player_1.20.1-11.1.0
- adaptive_performance_tweaks_spawn_1.20.1-11.1.0
- aesthetic-and-performant-1.5
- AI-Improvements-1.20-0.5.2
- alexs_caves_plus-1.1.2.3
- alexscaves-1.1.4
- alexscavesdelight-1.0.9-1.20.1
- alexsmobs-1.22.8
- alexsmobsinteraction-3.4-all
- AllTheCompatibility-1.20-(v.2.1.3)
- allthefood-1.1
- alltheores-1.20.1-47.1.3-2.2.4
- allthetrims-3.4.3-forge+1.20.1
- alternate_current-mc1.20-1.7.0
- amendments-1.20-1.2.8
- animated-doors-1.0
- AnimaticaReforged-1.20.1-0.1.3
- another_furniture-forge-1.20.1-3.0.1
- architectury-9.2.14-forge
- ars_creo-1.20.1-4.0.1
- ars_nouveau-1.20.1-4.9.0-all
- ars_ocultas-1.20.1-1.2.2-all
- async-locator-forge-1.20-1.3.0
- athena-forge-1.20.1-3.1.2
- AttributeFix-Forge-1.20.1-21.0.4
- Bad-Horse-Fix-2.0.0-forge
- BadOptimizations-2.1.4-1.20.1
- badpackets-forge-0.4.3
- balm-forge-1.20.1-7.3.6-all
- baubley-heart-canisters-1.20.1-1.0.3
- BetterAnimationsCollection-v8.0.0-1.20.1-Forge
- betterchunkloading-1.20.1-4.3
- bettercombat-forge-1.8.5+1.20.1
- betterfpsdist-1.20.1-4.4
- BetterModsButton-v8.0.2-1.20.1-Forge
- blahaj-forge-1.20.1-0.1.8
- Brute force Rendering Culling-forge-1.20.1-0.5.12
- Butters-CreateQuarkRecipe-1.20.1
- caelus-forge-3.2.0+1.20.1
- canary-mc1.20.1-0.3.3
- capes-1.5.2+1.20-forge
- carryon-forge-1.20.1-2.1.2.7
- catalogue-forge-1.20.1-1.8.0
- chefs-delight-1.0.3-forge-1.20.1
- Chipped-forge-1.20.1-3.0.6
- chisel-forge-1.20.1-1.8.0
- chunksending-1.20.1-2.8
- citadel-2.5.6-1.20.1
- ClearDespawn-forge-1.20.2-1.1.15
- cloth-config-11.1.118-forge
- clover-2024.0714
- Clumps-forge-1.20.1-12.0.0.4
- CodeChickenLib-1.20.1-4.4.0.512-universal
- connectivity-1.20.1-5.6
- Controlling-forge-1.20.1-12.0.2
- corn_delight-1.0.4-1.20.1
- coroutil-forge-1.20.1-1.3.7
- cozymagic_1.0.0-1.20.1-Forge
- CrabbersDelight-1.20.1-1.1.5a
- craftingtweaks-forge-1.20.1-18.2.4
- cratedelight-2024.07.12-1.20.1-forge
- create_jetpack_curios-1.0.0-forge-1.20.1
- create_jetpack-forge-4.2.1
- create_oppenheimered-1.0.3
- create_tab_fix-1.0.0+forge-1.20.1
- create-1.20.1-0.5.1.f
- create-man-of-many-planes-1.0
- create-structures-0.1.1-1.20.1-FORGE
- createaddition-1.20.1-1.2.4d
- createarmoryv0.6.1n
- creategoggles-1.20.1-0.5.5.g-[FORGE]
- CreativeCore_FORGE_v2.11.32_mc1.20.1
- creeperoverhaul-3.0.2-forge
- cupboard-1.20.1-2.7
- cursorcenteredfix-1.0
- decorative_blocks-forge-1.20.1-4.1.3
- deeperdarker-forge-1.20.1-1.2.1
- delightfulburgers-1.20.1
- delightfulsandwich-1.20.1
- DiagonalFences-v8.1.4-1.20.1-Forge
- do_a_barrel_roll-forge-3.5.6+1.20.1
- dynamic-fps-3.6.1+minecraft-1.20.0-forge
- dynamiccrosshair-7.4.4+1.20-forge
- DynamicTrees-1.20.1-1.3.0-BETA12
- DynamicTreesPlus-1.20.1-1.2.0-BETA3
- DynamicTreesQuark-1.20.1-2.5.3
- DynamicTreesTheTwilightForest-1.20.1-2.2.0-BETA2
- dynamictrim-1.4.1-forge+1.20.1
- dynview-1.20.1-4.0
- EasyLAN-v1.2-[1.20.1]
- EasyMagic-v8.0.1-1.20.1-Forge
- ec_ars_plugin-1.20.1-1.0.2-all
- elytraslot-forge-6.4.2+1.20.1
- elytratrims-forge-3.4.3+1.20.1
- embeddium-0.3.27+mc1.20.1
- EMI Create Schematics [1.0.0 Forge 1.20.1]
- emi_loot-0.6.6+fix3+1.20.1+forge
- emi-1.1.10+1.20.1+forge
- emi-letsdo-compat-forge-1.2
- EMIEnchants-forge-1.19.3-1.20.4-1.0.0
- emiffect-forge-1.1.2+mc1.20.1
- emitrades-forge-1.2.1+mc1.20.1
- enchantmentdisabletag-forge-1.1.0+1.20.1
- EnhancedVisuals_FORGE_v1.8.1_mc1.20.1
- entity_model_features_forge_1.20.1-2.1.3
- entity_texture_features_forge_1.20.1-6.1.3
- entityculling-forge-1.6.6-mc1.20.1
- EuphoriaPatcher-0.3.4-forge
- everycomp-1.20-2.6.68
- exordium-forge-1.2.1-mc1.20.1
- expanded_combat-1.20.1-3.1.2-all
- eyesoficeandfire-1.1.0-1.20.1
- fabric-api-0.92.2+1.11.8+1.20.1
- fabridge-0.0.4-R-1.20.1
- FancyBlockParticles-1.20.1-forge-20.1.0.2-beta
- FarmersDelight-1.20.1-1.2.4
- farsight-1.20.1-3.7
- fast-ip-ping-mc1.20.4-forge-v1.0.3
- fastasyncworldsave-1.20.1-2.0
- fastboot-1.20.x-1.1
- Fastload-Reforged-mc1.20.1-3.4.0
- fastpaintings-1.20-1.2.7
- Female-Gender-Mod-forge-1.20.1-3.1
- ferritecore-6.0.1-forge
- flywheel-forge-1.20.1-0.6.10-10
- ForgeClientResetPacket-0.3.1
- framework-forge-1.20.1-0.7.6
- fusion-1.1.1-forge-mc1.20.1
- geckolib-neoforge-1.20.1-4.4.7
- GeckoLibOculusCompat-Forge-1.0.1
- gpumemleakfix-1.20.1-1.8
- HeldItemTooltips-v8.0.0-1.20.1-Forge
- highlight-forge-1.20-2.0.1
- Highlighter-1.20.1-forge-1.1.9
- I18nUpdateMod-3.5.5-all
- iaf_patcher-0.1.1
- ice_and_fire_delight-forge-1.20.1-0.1.6
- iceandfire-2.1.13-1.20.1-beta-4
- Iceberg-1.20.1-forge-1.1.21
- ImmediatelyFast-Forge-1.2.18+1.20.4
- immersive_aircraft-1.0.1+1.20.1-forge
- immersive_armors-1.6.1+1.20.1-forge
- Incendium_1.20.x_v5.3.5
- Jade-1.20.1-forge-11.9.4
- justenoughbreeding-neoforge-1.20.1-1.3.0
- kleeslabs-forge-1.20-15.0.0
- kotlinforforge-4.11.0-all
- leaky-1.20.1-2.1
- LeavesBeGone-v8.0.0-1.20.1-Forge
- LegendaryTooltips-1.20.1-forge-1.4.5
- letmedespawn-forge-1.20.1-1.20.4-1.2.1
- Log-Begone-neoforge-1.20.1-1.0.9
- logprot-1.20.1-3.4
- LongerChatHistory-1.3-Forge
- majrusz-library-neoforge-1.20.1-7.0.8
- majruszs-accessories-neoforge-1.20.1-1.5.3
- man_of_many_planes-0.1.0+1.20.1-forge
- mcef-forge-2.1.5-1.20.1
  [🖿] mcef-libraries (folder)
- memoryleakfix-forge-1.17+-1.1.5
- mobtimizations-forge-1.20.1-1.0.0
- modelfix-1.15
- modernfix-forge-5.18.10+mc1.20.1
- ModernUI-Forge-1.20.1-3.10.1.4-universal
- modonomicon-1.20.1-forge-1.73.2
- mods_optimizer-forge-1.20.1-2.0.0
- moonlight-1.20-2.12.9-forge
- moredelight-2024.07.16-1.20.1-forge
- MouseTweaks-forge-mc1.20.1-2.25.1
- MyNethersDelight-1.20.1-0.1.7.5
- MyServerIsCompatible-1.20-1.0
- mysterious_mountain_lib-1.4.7-1.20.1
- Necronomicon-Forge-1.4.2
- Neruina-2.1.0-forge+1.20.1
- no-telemetry-1.8.0
- NoChatReports-FORGE-1.20.1-v2.2.2
- noisium-forge-2.0.3+mc1.20-1.20.1
- notenoughanimations-forge-1.7.4-mc1.20.1
- Nullscape_1.20.x_v1.2.7
- nyfsspiders-forge-1.20.1-2.1.1
- ObsidianUI-forge-0.2.3+mc1.20.1
- occultism-1.20.1-1.132.2
- oceansdelight-1.0.2-1.20
- octolib-1.20.1-0.3
- oculus-flywheel-compat-1.20.1-0.2.5
- oculus-mc1.20.1-1.7.0
- open-parties-and-claims-forge-1.20.1-0.23.2
- out_of_sight-1.20.1-1.0.3
- OverflowingBars-v8.0.0-1.20.1-Forge
- packetfixer-forge-1.4.2-1.19-to-1.20.1
- Patchouli-1.20.1-84-FORGE
- Ping-Wheel-1.9.1-forge-1.20.1
- player-animation-lib-forge-1.0.2-rc1+1.20
- polymorph-forge-0.49.5+1.20.1
- polytone-1.20-2.1.3
- potacore-0.2.8-universal
- PresenceFootsteps-1.20.1-1.9.1-beta.1
- Prism-1.20.1-forge-1.0.5
- PuzzlesLib-v8.1.21-1.20.1-Forge
- Quark-4.0-458
- QuarkOddities-1.20.1
- raccompat-1.20.1-0.1.2.1
- radiantgear-forge-2.1.5+1.20.1
- rainbowoaks-forge-1.20-1.0.1
- ramcompat-1.20.1-0.1.3
- rch-supplementaries-compat-forge-1.0.0
- refurbished_furniture-forge-1.20.1-1.0.2
- relics-1.20.1-0.6.5.2
- remote_player_waypoints_for_xaero-forge-3.1.0-1.20-1.20.1
- remove-terralith-intro-message-1.0
- resourcefulconfig-forge-1.20.1-2.1.2
- resourcefullib-forge-1.20.1-2.1.25
- right-click-harvest-3.2.3+1.20.1-forge
- ROGContinued-forge-1.2.1
- rubidium-extra-0.5.4.3+mc1.20.1-build.121
- RuOK-1.5.6_forge1.20.1
- RyoamicLights-forge-0.2.3+mc1.20.1
- saturn-mc1.20.1-0.1.3
- Searchables-forge-1.20.1-1.0.3
- servercore-forge-1.5.1+1.20.1
- servercountryflags-1.10.0-1.20.1-FORGE
- ShoulderSurfing-Forge-1.20.1-4.2.1
- shulkerboxslot-forge-5.1.1+1.20.1
- shulkerboxtooltip-forge-4.0.4+1.20.1
- Shut Up GL Error-forge-1.20.1-1.0.0
- skinlayers3d-forge-1.6.6-mc1.20.1
- slabsexpanded-1.20.1-1-forge
- sliceanddice-forge-3.2.1
- SmartBrainLib-forge-1.20.1-1.14.2
- smoothboot(reloaded)-mc1.20.1-0.0.4
- smoothchunk-1.20.1-3.6
- smoothswapping-0.9.2-1.20.1-forge
- sound-physics-remastered-forge-1.20.1-1.4.5
- spark-1.10.53-forge
- spawnanimations-v1.9.4-mc1.17x-1.20x-mod
- staaaaaaaaaaaack-forge-1.20.1-1.5-71
- starlight-1.1.2+forge.1cda73c
- Steam_Rails-1.6.4+forge-mc1.20.1
- storagedelight-2024.07.23-1.20.1-forge
- supplementaries-1.20-2.8.17
- suppsquared-1.20-1.1.14
- tectonic-forge-1.19.3-2.3.5a
- TerraBlender-forge-1.20.1-3.0.1.7
- Terralith_1.20.x_v2.5.4
- TF_Lost_Blocks-1.20.1-1.5.0
- torchflower_relit-1.0.0
- travelersbackpack-forge-1.20.1-9.1.15
- twilightdelight-2.0.11
- twilightforest-1.20.1-4.3.2508-universal
- vanillafix-1.0.0-forge-beta
- vegandelight-1.2
- VisualWorkbench-v8.0.0-1.20.1-Forge
- vmp-fabric-mc1.20.1-0.2.0+beta.7.101-all
- wardrobe-1.0.3.1-forge-1.20.1
- waveycapes-forge-1.4.8-mc1.20.1
- waystones-forge-1.20-14.1.4
- Xaeros_Minimap_24.2.0_Forge_1.20
- xaeros_waystones_compability-1.19.2-1.20.1--1.0
- XaerosWorldMap_1.38.8_Forge_1.20
- XaeroZoomout-Forge-1.20-1.1.0
- YetAnotherConfigLib-3.5.0+1.20.1-forge
- Zeta-1.0-19
- zume-1.1.1


This is probably the error:
`[20:27:35] [Worker-ResourceReload-8/ERROR] [minecraft/SpriteResourceLoader]: No key texture_name_as_folder in MapLike[{"type":"minecraft:ec_paletted_folder_permutations","textures":["expanded_combat:item/battle_staff","expanded_combat:item/broad_sword","expanded_combat:item/claymore","expanded_combat:item/cutlass","expanded_combat:item/dagger","expanded_combat:item/dancer_s_sword","expanded_combat:item/glaive","expanded_combat:item/katana","expanded_combat:item/scythe","expanded_combat:item/sickle","expanded_combat:item/spear","expanded_combat:item_large/battle_staff","expanded_combat:item_large/broad_sword","expanded_combat:item_large/claymore","expanded_combat:item_large/dancer_s_sword","expanded_combat:item_large/glaive","expanded_combat:item_large/katana","expanded_combat:item_large/scythe","expanded_combat:item_large/spear"],"palette_key":"expanded_combat:item/color_palettes/template","permutations":{"acacia_plank":"expanded_combat:item/color_palettes/acacia_plank","bamboo_plank":"expanded_combat:item/color_palettes/bamboo_plank","birch_plank":"expanded_combat:item/color_palettes/birch_plank","cherry_plank":"expanded_combat:item/color_palettes/cherry_plank","crimson_plank":"expanded_combat:item/color_palettes/crimson_plank","dark_oak_plank":"expanded_combat:item/color_palettes/dark_oak_plank","diamond":"expanded_combat:item/color_palettes/diamond","gold":"expanded_combat:item/color_palettes/gold","iron":"expanded_combat:item/color_palettes/iron","jungle_plank":"expanded_combat:item/color_palettes/jungle_plank","mangrove_plank":"expanded_combat:item/color_palettes/mangrove_plank","netherite":"expanded_combat:item/color_palettes/netherite","oak_plank":"expanded_combat:item/color_palettes/oak_plank","spruce_plank":"expanded_combat:item/color_palettes/spruce_plank","stone":"expanded_combat:item/color_palettes/stone","warped_plank":"expanded_combat:item/color_palettes/warped_plank"}}]; No key texture_name_as_folder in MapLike[{"type":"minecraft:ec_paletted_folder_permutations","textures":["expanded_combat:trims/items/gauntlet_trim"],"palette_key":"minecraft:trims/color_palettes/trim_palette","permutations":{"amethyst":"minecraft:trims/color_palettes/amethyst","copper":"minecraft:trims/color_palettes/copper","diamond":"minecraft:trims/color_palettes/diamond","diamond_darker":"minecraft:trims/color_palettes/diamond_darker","emerald":"minecraft:trims/color_palettes/emerald","gold":"minecraft:trims/color_palettes/gold","gold_darker":"minecraft:trims/color_palettes/gold_darker","iron":"minecraft:trims/color_palettes/iron","iron_darker":"minecraft:trims/color_palettes/iron_darker","lapis":"minecraft:trims/color_palettes/lapis","netherite":"minecraft:trims/color_palettes/netherite","netherite_darker":"minecraft:trims/color_palettes/netherite_darker","quartz":"minecraft:trims/color_palettes/quartz","redstone":"minecraft:trims/color_palettes/redstone"}}]
[20:27:35] [Worker-ResourceReload-8/WARN] [minecraft/SpriteResourceLoader]: Failed to parse atlas definition minecraft:atlases/blocks.json in pack expanded_combat-1.20.1-3.1.2-all.jar
java.lang.RuntimeException: No key texture_name_as_folder in MapLike[{"type":"minecraft:ec_paletted_folder_permutations","textures":["expanded_combat:item/battle_staff","expanded_combat:item/broad_sword","expanded_combat:item/claymore","expanded_combat:item/cutlass","expanded_combat:item/dagger","expanded_combat:item/dancer_s_sword","expanded_combat:item/glaive","expanded_combat:item/katana","expanded_combat:item/scythe","expanded_combat:item/sickle","expanded_combat:item/spear","expanded_combat:item_large/battle_staff","expanded_combat:item_large/broad_sword","expanded_combat:item_large/claymore","expanded_combat:item_large/dancer_s_sword","expanded_combat:item_large/glaive","expanded_combat:item_large/katana","expanded_combat:item_large/scythe","expanded_combat:item_large/spear"],"palette_key":"expanded_combat:item/color_palettes/template","permutations":{"acacia_plank":"expanded_combat:item/color_palettes/acacia_plank","bamboo_plank":"expanded_combat:item/color_palettes/bamboo_plank","birch_plank":"expanded_combat:item/color_palettes/birch_plank","cherry_plank":"expanded_combat:item/color_palettes/cherry_plank","crimson_plank":"expanded_combat:item/color_palettes/crimson_plank","dark_oak_plank":"expanded_combat:item/color_palettes/dark_oak_plank","diamond":"expanded_combat:item/color_palettes/diamond","gold":"expanded_combat:item/color_palettes/gold","iron":"expanded_combat:item/color_palettes/iron","jungle_plank":"expanded_combat:item/color_palettes/jungle_plank","mangrove_plank":"expanded_combat:item/color_palettes/mangrove_plank","netherite":"expanded_combat:item/color_palettes/netherite","oak_plank":"expanded_combat:item/color_palettes/oak_plank","spruce_plank":"expanded_combat:item/color_palettes/spruce_plank","stone":"expanded_combat:item/color_palettes/stone","warped_plank":"expanded_combat:item/color_palettes/warped_plank"}}]; No key texture_name_as_folder in MapLike[{"type":"minecraft:ec_paletted_folder_permutations","textures":["expanded_combat:trims/items/gauntlet_trim"],"palette_key":"minecraft:trims/color_palettes/trim_palette","permutations":{"amethyst":"minecraft:trims/color_palettes/amethyst","copper":"minecraft:trims/color_palettes/copper","diamond":"minecraft:trims/color_palettes/diamond","diamond_darker":"minecraft:trims/color_palettes/diamond_darker","emerald":"minecraft:trims/color_palettes/emerald","gold":"minecraft:trims/color_palettes/gold","gold_darker":"minecraft:trims/color_palettes/gold_darker","iron":"minecraft:trims/color_palettes/iron","iron_darker":"minecraft:trims/color_palettes/iron_darker","lapis":"minecraft:trims/color_palettes/lapis","netherite":"minecraft:trims/color_palettes/netherite","netherite_darker":"minecraft:trims/color_palettes/netherite_darker","quartz":"minecraft:trims/color_palettes/quartz","redstone":"minecraft:trims/color_palettes/redstone"}}]
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%2399!/:?] {re:mixin}
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%2399!/:?] {}
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%2399!/:?] {re:mixin}
	at net.minecraft.client.renderer.texture.atlas.SpriteResourceLoader.m_261166_(SpriteResourceLoader.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23690!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.renderer.texture.SpriteLoader.m_260769_(SpriteLoader.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23690!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:fusion.mixins.json:SpriteLoaderMixin,pl:mixin:APP:fastpaintings.mixins.json:ModelManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}`

**Comment by liavnk** [comment] 2024-07-24 19:06
i noticed that it only affects the different wood-types if that helps you i'm looking through your code rn

**Comment by liavnk** [comment] 2024-07-24 19:16
ok i think it's caused by the code [here](https://github.com/userofbricks/Expanded-Combat/blob/a00ab0dc0863b35eae8d04408fa7156826bf70af/src/main/java/com/userofbricks/expanded_combat/client/sprites/PalettedFolderPermutations.java#L46).

**Comment by liavnk** [comment] 2024-07-24 19:18
pls fix :(

**Comment by HatfieldS** [comment] 2024-07-30 04:51
Is there a fix for this issue, or not yet?

**Comment by userofbricks** [comment] 2024-07-30 17:19
not yet, Iv'e been really busy the last few weeks.

**Comment by userofbricks** [comment] 2024-07-30 18:00
@lunarydess Expanded Combat Works fine on its own and the textures are showing up. there must be a mod you are using that changes either how resource packs are read.

The code you pointed out is a custom atlas resource loader that is near identical to one created by vanilla mc. And the error you have given shows a resource pack error that dictates that one or all the resource packs added by mods doesn't have the required fields. which I have double checked and ec and the ars plugin you are using have ALL required values/fields.

What needs to happen now is parring down the list of mods your using to find out which one (or multiple) is causing this bug to occur. Then I might be able to create some sort of fix. but I don't have the time right now as I am getting ready for university. I might have time after classes start but updating the mod to 1.21 may take precedence over a niche bug I can't accurately replicate.

**Comment by liavnk** [comment] 2024-07-30 18:07
It's not that much of a big deal I use the mod nevertheless. I will investigate further in this when I have more time.
Good luck with the University, you got this. :)

**Comment by themapache** [comment] 2024-08-01 22:59
If it works for something, I have some of the mods that you were using and the one that was doing incompatibility for me was Dynamic Trims.

**Comment by liavnk** [comment] 2024-08-10 19:07
will definitely look into that @themapache, thanks :)

**Closed as completed** 2024-12-11 04:17 UTC
Labels: bug, invalid, wontfix, 1.20.1

**Comment by vildator** [comment] 2025-01-12 10:54
@themapache hi have you by any chance figured witch mod causes that? i have the same issue.

**Comment by themapache** [comment] 2025-01-14 20:27
It was Dynamic Trims

________________________________
