### ISSUE TITLE
Suggestion- EC addons/plugins - 1.20.1

### ISSUE THREAD

**Issue by zachsai** [userofbricks/Expanded-Combat#25] opened 2023-08-11 22:26 UTC
adding weapons, shields, gauntlets, etc. for such materials in thier respective mod(s):
[Create Chromatic Return](https://legacy.curseforge.com/minecraft/mc-mods/create-chromaticreturn)
Calorite ([Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra))
Ostrum ([Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra))
Desh ([Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra))

**Comment by userofbricks** [comment] 2023-08-12 02:33
I'll add it to the list of considerations!
[Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra)

**Comment by userofbricks** [comment] 2023-09-15 20:32
I've changed the main topic comment to better help me keep track of all the materials/mods that are possible to add support to.

mods completed:
[L_Ender's Cataclysm](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
Enderite ([Enderite CJ Edition](https://www.curseforge.com/minecraft/mc-mods/enderite-cj-edition))
Gilded Netherite ([Guilded Netherite CJ Edition](https://www.curseforge.com/minecraft/mc-mods/gilded-netherite-cj-edition))
[Advanced Netherite](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite)
[Epic Samuri](https://www.curseforge.com/minecraft/mc-mods/epic-samurais)
[Create](https://www.curseforge.com/minecraft/mc-mods/create)
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)

This list is outdated

**Comment by userofbricks** [comment] 2023-09-15 20:42
considering [Dreadsteel](https://www.curseforge.com/minecraft/mc-mods/dreadsteel), however that would also require Ice and Fire. need to check update status for ice and fire.

**Comment by userofbricks** [comment] 2023-09-15 20:44
considering [Aethersteel](https://www.curseforge.com/minecraft/mc-mods/aethersteel) but i need to check balancing stuff first.

**Comment by userofbricks** [comment] 2023-09-15 20:51
I might Consider [Extra Gems](https://www.curseforge.com/minecraft/mc-mods/extra-gems) however all the gems don't sound like things that should be the only material in thier respective weapons/shields/gauntlets

**Comment by userofbricks** [comment] 2023-09-15 20:56
[Silent Gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear) and its material mod [Silent's Gems](https://www.curseforge.com/minecraft/mc-mods/silents-gems) might be good mods to support however that is going to take a while to create. i think i will do it but at a much later date.

**Comment by userofbricks** [comment] 2023-09-15 21:07
[Epic Samuri](https://www.curseforge.com/minecraft/mc-mods/epic-samurais) and [Epic Knights](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons) would be fun to have support for.

**Comment by userofbricks** [comment] 2023-09-17 16:00
hmm it would require a base mod update but [L_Ender's Cataclysm](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm) could be made compatible if the shield bug gets fixed.

**Comment by YejiYeah** [comment] 2023-12-20 03:56
Please also add materials for Blue skies mod

**Comment by userofbricks** [comment] 2023-12-20 19:37
that would be a cool one to support

**Comment by YejiYeah** [comment] 2023-12-21 04:07
Thank you, User of bricks, I have more suggestions, should I open a new thread? , Actually I would like to make your mods as main mods for my modpack

**Comment by userofbricks** [comment] 2023-12-23 04:28
if the suggestions are for new materials, this would be the right thread. otherwise it would be easier for me to track if you could open a new one.

**Comment by YejiYeah** [comment] 2023-12-23 13:17
My suggestion is add the materials for the below mods:

- [x] * The Aether (Deep Aether, Lost Content Addon and Aether Redux)
- [x] * Blue Skies
- [ ] * Hardmode Progression Extended Material Tiers (this mod also change the durability of some material tiers (Ex. Diamond gear/tools), making late game materials more rewarding)
- [x] * Aquaculture 2
- [x] * Enderite mod
- [ ] * Biome Makeover
- [ ] * [Galosphere](https://www.curseforge.com/minecraft/mc-mods/galosphere)
- [ ] * Deeper and Darker

**Comment by userofbricks** [comment] 2023-12-23 18:54
Aquaculture already has a mod adding materials for it.

**Comment by YejiYeah** [comment] 2023-12-24 05:34
> Aquaculture already has a mod adding materials for it.

Thank you, installed Aquaculture, I noticed you have one enderite addon, is it possible to make that mod compatible with this one below, so any of them installed work with your mod, sorry if this request is not possible, I understand, I am newbie in these topics:

https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-forge 

Thank you!

**Comment by userofbricks** [comment] 2024-03-25 20:10
[galosphere](https://www.curseforge.com/minecraft/mc-mods/galosphere), for its silver stuff
doesn't need a whole weapon set, maybe a silver crossbow, quiver, shield, sterling gauntlets,and/or silver arrows

**Comment by userofbricks** [comment] 2024-03-29 18:11
[iron's spells n spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)

**Comment by ThePiekar** [comment] 2024-05-10 01:03
I think it's worth to consider a data-driven addon that would allow to add basic items sets with no extra behaviour based on a config file. This way modpack makers could provide textures (via a resource pack) and configs in order to get full material coverage (even if without the extra effects provided by official compats).
This idea is motivated mainly by the gauntlets, which (at least to my knowledge) couldnt be easily reproduced with simpler methods like kubejs.

**Comment by userofbricks** [comment] 2024-05-10 01:09
its a good idea. I've actually been toying around with adding something similar to the base mod. I've been wanting to  move much of the server sided config to a datapack format.

**Comment by goldrichman9Modded** [comment] 2024-08-14 05:44
> its a good idea. I've actually been toying around with adding something similar to the base mod. I've been wanting to move much of the server sided config to a datapack format.

how about [DivineRPG](https://www.curseforge.com/minecraft/mc-mods/official-divinerpg)

**Comment by TheMalevolentSun** [comment] 2024-09-05 13:04
I saw that you were concidering dreadsteel, if you are still looking into compatability with ice and fire I would love to see dragonsteel and dragon bone weapons as well, It's ever so mildy irritating that those materials are the only ones in my whole load order without respective weapon types

**Comment by IvoryJustie** [comment] 2024-10-12 07:05
> its a good idea. I've actually been toying around with adding something similar to the base mod. I've been wanting to move much of the server sided config to a datapack format.

Theres more plugin suggestions in #72

**Comment by userofbricks** [comment] 2024-12-16 21:59
I've added a project for expanded combat where I keep track of all created, released, and possible compatibility/plugin mods [here](https://github.com/users/userofbricks/projects/3).
And since there is another issue for addon/plugin suggestions I will close this issue for now.

**Closed as completed by userofbricks** 2024-12-16 21:59 UTC
Labels: enhancement, 1.20.1
